In [32]:
import cv2             #opencv library
import numpy as np     #numerical python 
import matplotlib.pyplot as plt     #math plot
from matplotlib.colors import LinearSegmentedColormap
import math
#Steven Taylor Edge Detection Assignment
#all credit for this program goes to Dr. Cameron
width = 4
height = 4

def makeImage():
    myImg= np.zeros([width,height], np.int16)  #initializing a new image
    myImg[0][0] = 25
    myImg[1][0] = 0
    myImg[2][0] = 0
    myImg[3][0] = 0
    myImg[0][1] = 25
    myImg[0][2] = 25
    myImg[0][3] = 20
    myImg[1][1]= 20
    myImg[1][2]= 0
    myImg[1][3] = 0
    myImg[2][1] = 25
    myImg[3][1] = 20
    myImg[3][3] = 0
    myImg[3][2]= 0
    myImg[2][2] = 20
    myImg[2][3] = 25
    print(myImg)
    '''
    [[25,25,25,20
    [0,20,0,0]
    [0,25,20,25]
    [0,20,0,0]]
    '''

    return myImg
def annotateImage(image, edgeImage):
    result = np.zeros([width,height], np.int16)  #initializing a new image  
    result = image.copy()
    for row in range(0, height):
        for col in range(0,width):
            if edgeImage[row,col] > 0:
                result[row,col] = 128
            
    return result
def imageDiff(image1, image2):
    #image1, image2  --> height x width array of unsigned 8bit integers
    #returns the absolute difference between image1 and image2
    diff = np.zeros([width,height], np.uint8)  #initializing a new image each pixel is an unsigned 8bit integer
    for row in range(0, height):
        for col in range(0,width):           
            if image1[row,col] > image2[row][col]:  #this check is performed since we are using unsigned integers  (no negatives)           
                diff[row,col] = image1[row,col] - image2[row,col]
            else:     
                diff[row,col] = image2[row,col] - image1[row,col]
    return diff
    
def edgeMaster(image):
    directions =[[0,-1],[-1,-1],[-1,0],[-1,1],[0,1],[1,1],[1,0],[1,-1]]
    watson = np.zeros([width,height], np.uint8)
    for row in range(0,height):
        for col in range(0,width):
            for i in range(0,8):
                neighborRow = row + directions[i][0]
                neighborCol = col + directions[i][1]
                if neighborRow >= 0 and neighborRow < height and neighborCol >= 0 and neighborCol < width:
                    if(image[row][col] != image[neighborRow,neighborCol]):
                        watson[row,col] = 255
    return watson
#mean abs func
def meanAbs(diffImg):
    sum =0 
    for row in range(0, height):
        for col in range(0, width):
            delta = int(diffImg[row,col])
            delta = delta * delta
            sum = sum + delta
    return math.sqrt(sum)/(width*height)

#diff expected vs calculated


#testImage = makeCheckerBoard(width/squareCount)
testImage = makeImage()
dst = cv2.GaussianBlur(testImage,(5,5),cv2.BORDER_DEFAULT)
print("Gauss", dst)
gDiff = imageDiff(dst, testImage)
print("Gaus Diff",gDiff)
annotatedImage = annotateImage(testImage,gradient)
sobelx = cv2.Sobel(testImage,cv2.CV_16S,1,0,ksize=3)  
sobely = cv2.Sobel(testImage,cv2.CV_16S,0,1,ksize=3)  
gradient = cv2.addWeighted(cv2.convertScaleAbs(sobelx), 0.5, cv2.convertScaleAbs(sobely), 0.5, 0)
print("Gradient", gradient)
sobelx2 = cv2.Sobel(dst,cv2.CV_16S,1,0,ksize=3)  
sobely2 = cv2.Sobel(dst,cv2.CV_16S,0,1,ksize=3)  
g2 = cv2.addWeighted(cv2.convertScaleAbs(sobelx2), 0.5, cv2.convertScaleAbs(sobely2), 0.5, 0)
print("Gauss Gradient", g2 )
sobelx3 = cv2.Sobel(gDiff,cv2.CV_16S,1,0,ksize=3)  
sobely3 = cv2.Sobel(gDiff,cv2.CV_16S,0,1,ksize=3)  
g3 = cv2.addWeighted(cv2.convertScaleAbs(sobelx3), 0.5, cv2.convertScaleAbs(sobely3), 0.5, 0)
print("Diff Gauss Gradient", g3)
g2Diff = imageDiff(g3, g2)
print(g2Diff)


[[25 25 25 20]
 [ 0 20  0  0]
 [ 0 25 20 25]
 [ 0 20  0  0]]
Gauss [[15 15 14 17]
 [14 14 11 14]
 [15 15 14 17]
 [12 12 10 14]]
Gaus Diff [[10 10 11  3]
 [14  6 11 14]
 [15 10  6  8]
 [12  8 10 14]]
Gradient [[ 0  0 25  0]
 [25 25 25  0]
 [ 0 20 20  0]
 [ 0 20 20  0]]
Gauss Gradient [[0 4 2 0]
 [0 4 2 0]
 [4 7 5 1]
 [0 3 4 0]]
Diff Gauss Gradient [[ 0  2  1  0]
 [ 5  7  6  0]
 [ 0 12  5  1]
 [ 0 11  4  0]]
[[0 2 1 0]
 [5 3 4 0]
 [4 5 0 0]
 [0 8 0 0]]
